name: Renovation Hell
favicon: null
layout_spectrum: 0.9782463707961142
typography_spectrum: 0.4746734232176095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9251593933440745
  lightness: 0.5013514193706214
  saturation: 0.29445661697536707
  rhythmicContrast: 0.6036834546830505
purpose: []
